### ISSUE TITLE
Support for modules

### ISSUE THREAD

**Issue by miguel-callejas-seagull-com** [jmccann/drone-artifactory#7]
Hi
Just realized that when building multiple jars as modules in a project, using this pipeline definition:

```
  artifactory_deploy:
    image: jmccann/drone-artifactory
    url: https://artifactory.mydomain.com
    username: admin
    password: password
    pom: pom.xml
    files:
      - ./**/target/*.jar
```

Will deploy all the jars under a single parent name in the artifactory. Is there any syntax to allow modules? I tried the `context: <folder-of-module>` as most of the drone plugins support it, but with no luck.

```

<distributionManagement>
    <repository>
        <id>central</id>
        <name>abc-releases</name>
        <url>http://artifactory.mydomain.com/artifactory/libs-release-local</url>
    </repository>
    <snapshotRepository>
        <id>snapshots</id>
        <name>abc-snapshots</name>
        <url>http://artifactory.mydomain.com/artifactory/libs-snapshot-local</url>
    </snapshotRepository>
</distributionManagement>


  <modules>
    <module>abc-commons-utils</module>
    <module>abc-commons-epc-transcoding</module>
    <module>abc-commons-encryption</module>
  </modules>

```
